### PR TITLE
generate API docs with Sphinx

### PR DESCRIPTION
**Pull request by hickford**
First step for #41

### CODE REVIEW

**Comment by hickford** [comment]
Tested, looks nice

image

**Comment by rspeer** [comment]
Thanks so much for the documentation!

One thing I'm noticing is that I wrote the docstrings in Markdown, but Sphinx expects RST, so occasionally the formatting isn't what I would have intended. I seem to recall that there's a plugin for Sphinx that lets it use Markdown - is this something you're familiar with?

**Comment by hickford** [comment]
Done

**Comment by rspeer** [comment]
Thanks. Going to try to follow up with this now that I've regained the ability to admin this repository.

**Comment by rspeer** [comment]
Following up: this is a good start but I think the output needs some work. I think the current output is a lot harder to read than the README.md. At the moment I'm not going to publish the generated documentation, because I'd prefer people just look at the README.

**Pull request merged**
